version: "3"

services:
  php:
    container_name: vd_docker_php
    build:
      context: docker/php
      dockerfile: Dockerfile
    networks:
      - vd_network
    environment:
      - APP_ENV=dev
    volumes:
      - ./app:/opt/app
      - ./docker/php/conf.d/custom-dev.ini:/usr/local/etc/php/conf.d/custom.ini

  nginx:
    container_name: vd_docker_nginx
    image: nginx
    networks:
      - vd_network
    ports:
      - 8080:80
    volumes:
      - ./app:/opt/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

networks:
  vd_network: